# These are supported funding model platforms

github: #yashprakash13 # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: 'buymeacoffee.com/hbeg' # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
